{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "db0aa593-b06f-40c0-a23b-6a68ae31c096",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "from streamlit_autorefresh import st_autorefresh\n",
    "import pandas as pd\n",
    "\n",
    "def generate_alerts(df):\n",
    "    alerts = []\n",
    "\n",
    "    for _, row in df.iterrows():\n",
    "\n",
    "        # Severe delay\n",
    "        if row[\"delay_min\"] >= 10:\n",
    "            alerts.append({\n",
    "                \"route\": row[\"route_id\"],\n",
    "                \"severity\": \"HIGH\",\n",
    "                \"message\": f\"Severe delay of {row['delay_min']:.1f} min at stop {row['stop_id']}\"\n",
    "            })\n",
    "\n",
    "        # Bunching\n",
    "        if row[\"is_bunched\"] == True:\n",
    "            alerts.append({\n",
    "                \"route\": row[\"route_id\"],\n",
    "                \"severity\": \"MEDIUM\",\n",
    "                \"message\": f\"Bunching detected near stop {row['stop_id']}\"\n",
    "            })\n",
    "\n",
    "        # Very short headway\n",
    "        if row[\"headway_min\"] <= 2:\n",
    "            alerts.append({\n",
    "                \"route\": row[\"route_id\"],\n",
    "                \"severity\": \"LOW\",\n",
    "                \"message\": f\"Very short headway ({row['headway_min']:.1f} min)\"\n",
    "            })\n",
    "\n",
    "    return pd.DataFrame(alerts)\n",
    "\n",
    "def show():\n",
    "    st.title(\"🚨 Real-Time Alerts Dashboard\")\n",
    "\n",
    "    st_autorefresh(interval=30_000, key=\"alerts_refresh\")\n",
    "\n",
    "    df = pd.read_csv(\"dummy_trip_updates.csv\")\n",
    "    df[\"arrival_dt\"] = pd.to_datetime(df[\"arrival_time\"], unit=\"s\")\n",
    "    df[\"delay_min\"] = df[\"delay\"] / 60\n",
    "    df[\"headway_min\"] = df.groupby([\"route_id\", \"stop_id\"])[\"arrival_dt\"].diff().dt.total_seconds() / 60\n",
    "    df[\"is_bunched\"] = df[\"headway_min\"] < 3\n",
    "\n",
    "    st.subheader(\"Live Feed (Last 20 Records)\")\n",
    "    st.dataframe(df.tail(20))\n",
    "\n",
    "    alerts = generate_alerts(df.tail(20))\n",
    "\n",
    "    st.subheader(\"Active Alerts\")\n",
    "\n",
    "    if alerts.empty:\n",
    "        st.success(\"No active alerts. System stable.\")\n",
    "    else:\n",
    "        for _, row in alerts.iterrows():\n",
    "            if row[\"severity\"] == \"HIGH\":\n",
    "                st.error(f\"[{row['route']}] {row['message']}\")\n",
    "            elif row[\"severity\"] == \"MEDIUM\":\n",
    "                st.warning(f\"[{row['route']}] {row['message']}\")\n",
    "            else:\n",
    "                st.info(f\"[{row['route']}] {row['message']}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
